import type { Exercise, Program } from '../types'

function ex(partial: Omit<Exercise, 'id'> & { id: string }): Exercise {
  return partial
}

export function buildSeedProgram(): Program {
  return {
    id: 'programme-1',
    name: 'Programme Maman',
    sessions: [
      {
        id: 'mardi',
        name: 'Mardi — Mobilité + ceinture pelvienne',
        exercises: [
          ex({
            id: 'm-mar-1',
            name: 'Contraction + assouplissement bras tendu',
            sets: 3,
            reps: '5 x (5s/5s) / bras',
            repos: 60,
            note: 'Bras tendu devant toi : contracte 5s puis relâche/étire 5s, alterne par bras.',
          }),
          ex({
            id: 'm-mar-2',
            name: 'Circle',
            sets: 3,
            reps: '6',
            repos: 60,
            note: "Allongé au sol, trace un grand cercle avec le bras en cherchant l'amplitude max : va devant puis repars derrière, rotation du poignet à 180° au milieu.",
          }),
          ex({
            id: 'm-mar-3',
            name: 'Squat profond',
            sets: 3,
            reps: '30-45s',
            repos: 60,
            note: 'Descends en squat complet et reste en bas, dos droit, le temps indiqué.',
          }),
          ex({
            id: 'm-mar-4',
            name: 'Dead bug',
            sets: 3,
            reps: '12',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Allongé sur le dos, bas du dos plaqué au sol, étends bras et jambe opposés en alternance.',
          }),
          ex({
            id: 'm-mar-5',
            name: 'Superman',
            sets: 3,
            reps: '20-30s',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Ventre au sol, lève bras et jambes tendus et maintiens.',
          }),
          ex({
            id: 'm-mar-6',
            name: 'Palof OH 1 jambe',
            sets: 3,
            reps: '6/côté',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Palof press en équilibre sur une jambe, bras au-dessus de la tête, résiste à la rotation.',
          }),
          ex({
            id: 'm-mar-7',
            name: 'Farmer carry',
            sets: 3,
            reps: '20m/côté',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Marche en portant une charge lourde, garde le dos droit.',
          }),
          ex({
            id: 'm-mar-8',
            name: 'Tirage horizontal',
            sets: 3,
            reps: '16-20/côté',
            repos: 120,
            intensite: 'RPE 7',
            note: 'Rowing classique (élastique ou poulie), coudes vers l\'arrière.',
          }),
        ],
      },
      {
        id: 'jeudi',
        name: 'Jeudi — Prévention full body + Renfo triceps',
        exercises: [
          ex({
            id: 'm-jeu-1',
            name: 'Pistol squat banc',
            sets: 3,
            reps: '6/côté',
            repos: 180,
            intensite: 'RPE 7-8',
            note: 'Squat une jambe assisté par le banc.',
          }),
          ex({
            id: 'm-jeu-2',
            name: 'Pompes excentrique',
            sets: 3,
            reps: '6-10',
            repos: 180,
            intensite: 'RPE 7-8',
            note: 'Pompes en ralentissant la descente au maximum.',
          }),
          ex({
            id: 'm-jeu-3',
            name: 'Ponté pelvien + abduction',
            sets: 3,
            reps: '12',
            repos: 180,
            intensite: 'RPE 7-8',
            note: 'Pont fessier au sol, écarte les genoux (élastique) en haut du mouvement.',
          }),
          ex({
            id: 'm-jeu-4',
            name: 'Extension triceps',
            sets: 3,
            reps: '10',
            repos: 180,
            intensite: 'RPE 7-8',
            note: 'Extension du coude en charge (haltère ou élastique), cible le triceps.',
          }),
          ex({
            id: 'm-jeu-5',
            name: 'OH squat avec élastique',
            sets: 3,
            reps: '8-12',
            repos: 180,
            intensite: 'RPE 7-8',
            note: 'Squat bras tendus au-dessus de la tête, élastique placé autour des genoux.',
          }),
          ex({
            id: 'm-jeu-6',
            name: 'Bird dog',
            sets: 3,
            reps: '6/côté',
            repos: 180,
            intensite: 'RPE 7-8',
            note: 'Quadrupédie, étends bras et jambe opposés en gardant le dos stable.',
          }),
        ],
      },
      {
        id: 'samedi',
        name: 'Samedi — Mobilité + renfo full body',
        exercises: [
          ex({
            id: 'm-sam-1',
            name: 'Cars assis',
            sets: 3,
            reps: '6/côté',
            repos: 90,
            note: "Rotation articulaire contrôlée de la hanche, assis : cherche l'amplitude max dans tous les sens.",
          }),
          ex({
            id: 'm-sam-2',
            name: 'IYT',
            sets: 3,
            reps: '6',
            repos: 90,
            note: 'Ventre au sol, lève bras et jambe ensemble en 3 positions : vers l\'arrière, puis en croix (T), puis en Y devant toi, et reviens.',
          }),
          ex({
            id: 'm-sam-3',
            name: 'Pigeon pose dynamique',
            sets: 3,
            reps: '8/côté',
            repos: 90,
            note: "Posture du pigeon en mouvement répété, cherche l'amplitude max à chaque répétition.",
          }),
          ex({
            id: 'm-sam-4',
            name: 'Step back élastique',
            sets: 3,
            reps: '12/côté',
            repos: 120,
            intensite: 'RPE 8-9',
            note: 'Debout sur un banc, descends une jambe jusqu\'à toucher le sol en contrôlant un maximum la descente, puis remonte.',
          }),
          ex({
            id: 'm-sam-5',
            name: 'Reverse nordic curl',
            sets: 3,
            reps: '10',
            repos: 120,
            intensite: 'RPE 8-9',
            note: 'À genoux, bascule en arrière en gardant le corps droit, freine avec les cuisses.',
          }),
          ex({
            id: 'm-sam-6',
            name: 'Thruster haltère',
            sets: 3,
            reps: '10',
            repos: 120,
            intensite: 'RPE 8-9',
            note: 'Squat complet enchaîné avec une poussée des haltères au-dessus de la tête.',
          }),
          ex({
            id: 'm-sam-7',
            name: 'Bar au front',
            sets: 3,
            reps: '8-12',
            repos: 120,
            intensite: 'RPE 8-9',
            note: 'Allongé, descends la barre vers le front (extension triceps).',
          }),
        ],
      },
    ],
  }
}
